### ISSUE TITLE
Any way to scale queue transfer rules in taskrouter?

### ISSUE THREAD

**Issue by sbaar** [twilio-professional-services/plugin-chat-sms-transfer#22]
I can implement the transfer to individual agent rule with one filter and one expression

`transferTargetType == 'worker'` and `worker.sid == task.targetSid` respectively. 

However, I can't figure out how to dynamically route to a queue without making a filter rule for each one and checking for `task.targetSid == WQ6407...`

(btw, please add #15 answer to the documentation, as it seem required and undocumented)

Otherwise, it's working great!

**Comment by johnfischelli** [comment]
Hey @sbaar, to my knowledge you're absolutely right - when transferring to a queue you unfortunately have to setup a filter in your workflow for each queue. It's due to how the Workflow's work.

Flex's voice **transfers** actually route tasks/calls to agents without running them through the workflow again, in the future I expect native chat transfers to work similarly, but until then if you want to transfer chats to queues, you'll need a filter for each.

I'm not sure when you initially installed the plugin but I was made aware of an issue (#21)  that could affect you yesterday and was fixed yesterday in #20 

There were changes both to the plugin itself and the provided Twilio Serverless Function that actually performs the transfer, so be sure to update both!

**Comment by jonathan-vouch** [comment]
Yeah also had to do this and expected their to be a better way of doing it. In the end we decided not to use Queues for chat, but good to know this is the only way to do it if we do put it back in! @johnfischelli would it be possible for you to provide your task router rules for comparison. I think I've done it in a similar way to @sbaar , but always good to have a reference to make sure nothing is being missed! :)

**Comment by johnfischelli** [comment]
Sure - here is an example of a workflow I maintain purely for demonstration purposes in my personal Twilio account handling both direct to agent and queue transfer scenarios.

```{
  "task_routing": {
    "filters": [
      {
        "filter_friendly_name": "Find Specific Agent",
        "expression": "transferTargetType == 'worker'",
        "targets": [
          {
            "queue": "WQ...",
            "expression": "worker.sid == task.targetSid"
          }
        ]
      },
      {
        "filter_friendly_name": "Everyone Queue",
        "expression": "transferTargetType == 'queue' && targetSid == 'WQ...'",
        "targets": [
          {
            "queue": "WQ..."
          }
        ]
      },
      {
        "filter_friendly_name": "Sales Queue",
        "expression": "transferTargetType == 'queue' && targetSid == 'WQ...'",
        "targets": [
          {
            "queue": "WQ..."
          }
        ]
      },
      {
        "filter_friendly_name": "Support Queue",
        "expression": "transferTargetType == 'queue' && targetSid == 'WQ...'",
        "targets": [
          {
            "queue": "WQ..."
          }
        ]
      },
      {
        "filter_friendly_name": "Gold Support Queue",
        "expression": "transferTargetType == 'queue' && targetSid == 'WQ...'",
        "targets": [
          {
            "queue": "WQ..."
          }
        ]
      }
    ],
    "default_filter": {
      "queue": "WQ..."
    }
  }
}```
